void main() {
  print("Variáveis Funções");

  print('Funções para o tipo int');

  num pi = 3.14;
  print(pi.floor());
  print(pi.round());
  print(pi.ceil());
  print(pi.clamp(3, 3.1));
  print(pi.compareTo(3));
  print(pi.remainder(3));
  print(pi.toInt());
  print(pi.toDouble());
  print(pi.toString());
  print(pi.toStringAsFixed(1));
  print(pi.truncate());
  print(pi.isNegative);
  print(pi.isInfinite);
  print((pi / 0).isInfinite);
  print(12.gcd(16));
  print('1'.padLeft(2, '0'));
  print('');
  print('Funções para o tipo String');
  print('');
  String nome = "Gabriel";
  String nomeCompleto = "\t Gabriel Estéfono";
  print(nome.toLowerCase());
  print(nome.toUpperCase());
  print(nomeCompleto.trim());
  print(nomeCompleto.split(' '));
  print(nome.split(''));
  print(nomeCompleto.substring(3, 8));
  print(nome.startsWith('G'));
  print(nome.startsWith('el', 5));
  print(nome.replaceAll('a', 'o'));
  print(nome.replaceFirst("Ga", "Da"));
  print(nome.replaceFirst("b", "d", 2));
  print(nome.replaceRange(3, 5, ''));
  print(nomeCompleto.trim().split(' '));
  print(nome.contains('g'));
  print(nome.contains('G', 0));
  print(nome.indexOf("el"));
  print(nome.length);
  print(nome.endsWith('o'));
  print(nome.compareTo('Gabriel'));
  print(nome.compareTo("el"));
  print(nome.compareTo("Abel"));
  print(nome.isEmpty);
  print(double.parse('12.55'));
  print(nome is String);
  print(int.parse('12') is int);
  print(nome.lastIndexOf('a'));
  String sopa = "Sopa de letrinhas";
  int index = sopa.indexOf(" de ");
  print("A sopa é${sopa.substring(index)}!");
  print('');
  num numero = 3.14;
  print(numero is double);
  print(numero is! double);
}
